### ISSUE TITLE
Issue with type: many

### ISSUE THREAD

**Issue by th-lange** [philiplb/CRUDlex#102]
# crud.yml
```yml
user:
  label: User
  table: user
  listFields: [id, email, user_role]
  filter: [email, user_role]
.........
    user_role:
      type: many
      label: Roles
      many:
        hideId: true
        entity: role
        nameField: group
        thisField: user_id
        thatField: role_id
```

Leads to the error:

> An exception has been thrown during the rendering of a template ("An exception occurred while 
> executing 'SELECT id,`group` FROM `role` t1 WHERE deleted_at IS NULL ORDER BY group ASC':

I think the ORDER BY `group` ASC should be like \`group\`.
