### ISSUE TITLE
Duplicate fields in crud.yml

### ISSUE THREAD

**Issue by jmfayard** [philiplb/CRUDlex#72]
Given a `crud.yml`containing 

I made a couple of times a mistake where I add two times the same attribute

```yml
user:
    label: User
    table: user
    fields:
        attribute:
            type: integer
            unique: true
        attribute:
            type: text
            unique: false
```

The one I was modifying was silently ignored, keeping me confused why nothing I did was taken into account.

If would be good if the validation step can add a warning here.
