### ISSUE TITLE
Prefilled Form Fields on the Creation Page doesn't work

### ISSUE THREAD

**Issue by k20human** [philiplb/CRUDlex#76]
In the [doc](http://philiplb.github.io/CRUDlex/docs/html/0.11.0/manual/extendedfeatures.html#prefilled-form-fields-on-the-creation-page) it's mention that we can prefilled fields with GET parameters

But when i try it doesn't work ... Did i miss something?

Here is my crud.yml:
```
difficulty:
    label: Difficulté
    table: difficulty
    fields:
        name:
            type: text
            label: Nom
```

I try this : http://localhost:8181/index_dev.php/crud/difficulty/create?name=toto
And my "Name" field is empty
